require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Links in development emails are normal http links to the API on the Mac's Wi-Fi address,
  # e.g. http://192.168.1.77:3000/dev/open-app/confirm-email?token=... That page (development
  # only, Dev::OpenAppController) then opens the app in Expo Go at Metro's address:
  # exp://192.168.1.77:8081/--/confirm-email?token=... (iOS ignores exp:// links inside
  # letter_opener_web's iframes). Set APP_LINK_BASE to override the email link base
  # (Android emulator, another port, or `expo start --tunnel`). See mobile/README.md.
  lan_ip = Socket.ip_address_list.find { |address| address.ipv4_private? }&.ip_address || "127.0.0.1"
  config.x.expo_go_link_base = "exp://#{lan_ip}:8081/--"
  config.x.app_link_base = ENV.fetch("APP_LINK_BASE", "http://#{lan_ip}:3000/dev/open-app").chomp("/")

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Emails are not sent in development: they are kept on disk (tmp/letter_opener) and
  # listed at http://localhost:3000/letter_opener, also from the phone at
  # http://<Mac Wi-Fi address>:3000/letter_opener when the server runs with -b 0.0.0.0.
  # Templates can still be previewed at /rails/mailers (spec/mailers/previews).
  config.action_mailer.delivery_method = :letter_opener_web
  config.action_mailer.preview_paths = [ Rails.root.join("spec/mailers/previews").to_s ]

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
